df_train:
  path_to_data: /home/jupyter/datasphere/project/snow_leopard_detection/animals_dataset_train.csv
  
df_val:
  path_to_data: /home/jupyter/datasphere/project/snow_leopard_detection/animals_dataset_val.csv

train_loader:
  batch_size: 8
  shuffle: True
  pin_memory: True
  num_workers: 6

val_loader:
  batch_size: 8
  shuffle: False
  pin_memory: True
  num_workers: 6

model:
  num_classes: 10
  num_features: 768
  m: 0.8
  s: 30.0

optimizer:
  learning_rate1: 0.0001
  learning_rate2: 0.00001

train_fn:
  epochs1: 10
  epochs2: 5
  model_path: /home/jupyter/datasphere/project/snow_leopard_detection/checkpoints/animal_classification.ckpt